### ISSUE TITLE
before-init-time

### ISSUE THREAD

**Issue by purcell** [davep/uptimes.el#1]
Would it make sense to use the built-in `before-init-time` in order to determine the startup time of the current instance? It might make `uptimes` more accurate and less sensitive to when it is loaded during an Emacs session.

**Comment by davep** [comment]
Sounds like an excellent idea, either that wasn't a thing when I first wrote this or I didn't look hard enough. I'll look to adding this when I'm next at my desk.

**Comment by davep** [comment]
Seems to work a treat. Thanks for the feedback.
