### ISSUE TITLE
Incompatibility with standalone cl-lib package

### ISSUE THREAD

**Issue by purcell** [davep/uptimes.el#2]
It appears that only the `cl-lib` bundled with the latest Emacs versions has `cl-flet*`: the [standalone `cl-lib` package](https://elpa.gnu.org/packages/cl-lib-0.6.1.el) does not. This is likely an issue with that package, which Stefan Monnier would want to fix if one of us lets him know, but it appears that a workaround in the meantime would be for `uptimes` to use `cl-letf*` instead.

(You can see the byte compilation errors/warnings in the various jobs of this build: https://travis-ci.org/purcell/emacs.d/builds/216883163)

**Comment by davep** [comment]
Thanks, I'll try and take a look at this tomorrow (or Saturday -- I'll be on a train for abut 8 hours so will need something to amuse me ;) ).

**Comment by davep** [comment]
Can I just confirm? The problem is with versions of GNU emacs older than 24.x? This will be about supporting "older" versions of emacs?

(sorry if the question seems daft, I've not paid much attention to the state of cl vs cl-lib and why it call changed -- happened during the years when I wasn't doing much elisp hacking)

**Comment by purcell** [comment]
Not only those: it's potentially some of the 24.x Emacs versions too. If you click on the builds link above and search in the Emacs 24.1 or 24.2 jobs for the byte compilation messages about `uptimes`, you'll find that it's not compiling cleanly there either.

**Comment by davep** [comment]
Okay, thanks, I think I'm struggling to follow and understand the content of that page as I'm not obviously seeing that; but I'm happy to take your word for it.

Looking at this I'd say that `cl-letf*` isn't really a good workaround for `cl-flet*` -- it'd make for code that's less clean in my opinion. I'll look at doing things a little different instead.

**Comment by davep** [comment]
I believe https://github.com/davep/uptimes.el/commit/88508ba583a0f4f54bca44fea8b39e21e80ed504 should handle this. Sorry, I'm not really in a position to test other emacs at the moment. I'll keep this issue open until you can give the all clear.

Thanks again for letting me know.

**Comment by purcell** [comment]
Still a bit broken in [23.4](https://travis-ci.org/purcell/emacs.d/jobs/216883164#L5079), though in [early 24.x versions](https://travis-ci.org/purcell/emacs.d/jobs/216883169#L4821) it seems to work fine despite some byte-compilation warnings. I'd suggest just adding `(emacs "24")` to your `Package-Requires` line... :-)

**Comment by davep** [comment]
That's really helpful, thanks.

Also.... the mystery of why I could not follow what you were pointing at the previous day is now solved. I was working via train WiFi and it looks like the logs themselves were flat out not loading, or were taking far too long they never finished loading. Now I'm home again it's all visible and obvious. :D

**Comment by davep** [comment]
emacs 24 is [now required](https://github.com/davep/uptimes.el/releases/tag/v3.3).

**Comment by purcell** [comment]
Awesome, thanks!
