### ISSUE TITLE
Licence of uptimes.el

### ISSUE THREAD

**Issue by brandelune** [davep/uptimes.el#3]
Hi,

In a thread in the emacs-devel maillist, the licensing situation for emacs packages provided through Emacs package archives has been under focus. I have volunteered to contact the authors of packages that have a license that is incompatible with Emacs, which is now under GPL-3+.

See https://lists.gnu.org/archive/html/emacs-devel/2017-07/msg01069.html

So I wonder if you could consider to change the license of your package to GPL-3+?

Yours,

Jean-Christophe Helary

**Comment by davep** [comment]
Thanks. The licence already is GPL-3+. I made the change [about 10 days ago](https://github.com/davep/uptimes.el/commit/9d7cfab317b0c69d8dc50d267288b97a9aeed798). :)

**Comment by brandelune** [comment]
Apologies ! Thank you for that !

Jean-Christophe

**Comment by davep** [comment]
No apology needed. Happy to help. Saw the thread at the time and went through most of my elisp code and bumped the licence so it would (hopefully) be more helpful.
